name: simplyputapp
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  lottie: ^3.1.2
  firebase_core: ^3.3.0
  profile: ^0.0.1
  smooth_page_indicator: ^1.2.0+3
  get: ^4.6.6
  modular_ui: ^0.0.5
  flutter_svg: ^2.0.10+1
  flashy_tab_bar2: ^0.0.10
  firebase_auth: ^5.1.4
  file_picker: ^8.0.7
  open_file: ^3.4.0
  path_provider: ^2.1.4
  google_mlkit_text_recognition: ^0.13.0
  image_cropper: ^8.0.2
  image_picker: ^1.1.2
  google_mlkit_document_scanner: ^0.2.0
  flutter_lints: ^4.0.0
  riverpod_annotation: ^2.3.5
  hooks_riverpod: ^2.5.2
  flutter_hooks: ^0.20.5
  flutter_dotenv: ^5.1.0
  syncfusion_flutter_pdf: ^26.2.11
  pinecone: ^0.7.2
  langchain_google: ^0.6.2
  langchain_pinecone: ^0.1.0+8
  langchain: ^0.7.5

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/app_assets/
    - assets/images/
