name: simplyputapp
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  lottie: ^3.1.2
  firebase_core:
  profile: ^0.0.1
  smooth_page_indicator: ^1.2.0+3
  get: ^4.6.6
  modular_ui: ^0.0.5
  flutter_svg: ^2.0.10+1
  flashy_tab_bar2: ^0.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/app_assets/
    - assets/images/
