// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPwDazoMJq3VZhRiKzXaE8QC025vTUBtg',
    appId: '1:101001326959:web:d4b9817a39c8d67f07389a',
    messagingSenderId: '101001326959',
    projectId: 'simplyput-flutter',
    authDomain: 'simplyput-flutter.firebaseapp.com',
    storageBucket: 'simplyput-flutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPpeyFCeLyHvIzhyIwabIDa1K___Abdi8',
    appId: '1:101001326959:android:a8964d266f0b6a4c07389a',
    messagingSenderId: '101001326959',
    projectId: 'simplyput-flutter',
    storageBucket: 'simplyput-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWc9tClTkfFIBazndEkP2FbY_K_fwOZLs',
    appId: '1:101001326959:ios:d4e15308ae35b84507389a',
    messagingSenderId: '101001326959',
    projectId: 'simplyput-flutter',
    storageBucket: 'simplyput-flutter.appspot.com',
    iosBundleId: 'com.example.simplyputapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWc9tClTkfFIBazndEkP2FbY_K_fwOZLs',
    appId: '1:101001326959:ios:d4e15308ae35b84507389a',
    messagingSenderId: '101001326959',
    projectId: 'simplyput-flutter',
    storageBucket: 'simplyput-flutter.appspot.com',
    iosBundleId: 'com.example.simplyputapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPwDazoMJq3VZhRiKzXaE8QC025vTUBtg',
    appId: '1:101001326959:web:00a72af4b56d1e8007389a',
    messagingSenderId: '101001326959',
    projectId: 'simplyput-flutter',
    authDomain: 'simplyput-flutter.firebaseapp.com',
    storageBucket: 'simplyput-flutter.appspot.com',
  );
}
